name: Build mpy_lvgl bin

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: clone lvgl
        run: |
          git clone https://github.com/lvgl/lv_micropython.git
          git clone https://github.com/nexus166/st77xx_mpy.git
          cd lv_micropython
          git submodule update --init --recursive lib/lv_bindings


      - name: Install dep and esp-idf
        run: |
          sudo apt-get install git wget flex bison gperf python3 python3-venv python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0 -y
          git clone --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          git checkout v4.4
          git submodule update --init --recursive
          ./install.sh

      - name: Build
        run: |
          source ./esp-idf/export.sh
          cd lv_micropython
          make -C mpy-cross
          cd ports/esp32
          make submodules
          make USER_C_MODULES=../../../st77xx_mpy/st77xx all
          make BOARD=GENERIC_SPIRAM
          mkdir upload
          cp build-GENERIC_SPIRAM/firmware.bin upload
 
      - name: Upload
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: build
          build_dir: ./lv_micropython/ports/esp32/upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
