name: Build mpy_lvgl bin

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: clone lvgl
        run: |
          git clone https://github.com/lvgl/lv_micropython.git
          cd lv_micropython
          git submodule update --init --recursive lib/lv_bindings


      - name: Install dep and esp-idf
        run: |
          sudo apt-get install git wget flex bison gperf python3 python3-venv python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0 -y
          git clone --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          git checkout v4.4
          git submodule update --init --recursive

      - name: Build
        run: |
          source ./esp-idf/export.sh
          cd lv_micropython
          make -C mpy-cross
          make -C ports/esp32 LV_CFLAGS="-DLV_COLOR_16_SWAP=1" BOARD=GENERIC_SPIRAM depoly

      - name: Upload
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: build
          build_dir: ./lv_micropython/build-GENERIC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
